### ISSUE TITLE
'View on GitHub' 404

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-url-helpers-lab#2]
<img width="398" alt="screen shot 2016-01-06 at 9 58 46 pm" src="https://cloud.githubusercontent.com/assets/14326883/12154607/cc8a2248-b4c0-11e5-8d22-b96c49a2305a.png">

https://github.com/learn-co-students/rails-url-helpers-lab-v-000

**Comment by AnnJohn** [comment]
hi @onyoo sorry about this. working on getting this resolved as quickly as we can. thanks!

**Comment by onyoo** [comment]
No worries! I'm going to bed and will pick-up again in a few hours.

**Comment by AnnJohn** [comment]
it's been fixed so should be working. but have a good night!

**Comment by onyoo** [comment]
Still doesn't seem to be resolved:

<img width="389" alt="screen shot 2016-01-07 at 11 05 08 am" src="https://cloud.githubusercontent.com/assets/14326883/12167803/a278ec46-b52e-11e5-8e9c-37a82658ab55.png">

https://github.com/learn-co-students/rails-url-helpers-lab-v-000
